services:
  phpfpm:
    image: php:8.4-fpm
    container_name: phpfpm
    build: docker/php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./public:/var/www/html:ro,cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
    depends_on:
      - phpfpm
    networks:
      - app-network

  postgresql:
    image: postgres:16
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs/postgresql:/var/log/postgresql
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge